### ISSUE TITLE
Add new Topic Subscription does not work

### ISSUE THREAD

**Issue by malebuffy** [hivemq/hivemq-mqtt-web-client#5]
i have used the files for my own web site to test the functionality. Publishing topics works as expected, however Subscribing cannot be tested because when pressing the button "Add New Topic Subscription", no window opens like the one on the demo in the HiveMQ website.

**Comment by pglombardo** [comment]
Hi @malebuffy - this isssue has gone stale.  Apologies for the lack of response.

If this is still an issue for you, could you let us know?  We have a new websocket in Beta to be released soon so I suspect this will be a nil issue going forward with the new client.

I'll close this issue out but feel free to open another if it persists.
