### ISSUE TITLE
all settings lost after reboot

### ISSUE THREAD

**Issue by atuxnull** [hivemq/hivemq-mqtt-web-client#9]
Hi. Running hivemq web client locally in a raspberry. all seems good, but after a reboot all settings are lost.
is there a way to make them persisent, please?

**Comment by dobermai** [comment]
Hi @atuxnull,

at the moment there is no way to retain the settings. We are willing to accept pull requests for such a feature, though.

**Comment by atuxnull** [comment]
Thanks a lot for your reply. Is there a workaround?

**Comment by dobermai** [comment]
I'm afraid there is no known workaround we are aware of.

The quickest thing I could think of is use a browser plugin which fills in the fields you want.

**Comment by pglombardo** [comment]
Hi @atuxnull - Thanks for pointing this out but considering the age I'm going to close out this issue.

Also note that there is an entirely new websocket client in the works that will be released soon.

You can try this new client out now - it's part of [HiveMQ Cloud](https://www.hivemq.com/mqtt-cloud-broker/).  Getting the source prepped and onto Github is still in progress.

<img width="1342" alt="Screenshot 2022-11-28 at 10 19 23" src="https://user-images.githubusercontent.com/395132/204889614-c8fc7923-7382-44e2-a052-3da5f1cd27ed.png">

Thanks again and if anything remains, feel free to open another issue or contact us in the [HiveMQ community forum](https://community.hivemq.com).
